# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default='89df3664cbfd4bd6a2a5991bb1445bab', primary_key=True, serialize=False)),
                ('contract', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
